<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="DSAExperimentation.Tests" />
    <InternalsVisibleTo Include="DSAExperimentation.Benchmarks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DSAExperimentation\DSAExperimentation.csproj" />
  </ItemGroup>

</Project>
