<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="DSAExperimentation.LeetCode" />
    <InternalsVisibleTo Include="DSAExperimentation.Tests" />
    <InternalsVisibleTo Include="DSAExperimentation.Benchmarks" />
    <InternalsVisibleTo Include="DSAExperimentation.LeetCode.Tests" />
    <InternalsVisibleTo Include="DSAExperimentation.Benchmarks.Tests" />
  </ItemGroup>

</Project>
